from datetime import datetime
from math import *
from Monica_Evapotranspiration.evapotranspiration import model_evapotranspiration
def model_evapotranspirationcomp(float evaporation_zeta,
      float maximum_evaporation_impact_depth,
      int no_of_soil_layers,
      float layer_thickness[no_of_soil_layers],
      float reference_albedo,
      float stomata_resistance,
      int evaporation_reduction_method,
      float xsa_critical_soil_moisture,
      float external_reference_evapotranspiration,
      float height_nn,
      float max_air_temperature,
      float min_air_temperature,
      float mean_air_temperature,
      float relative_humidity,
      float wind_speed,
      float wind_speed_height,
      float global_radiation,
      int julian_day,
      float latitude,
      float evaporated_from_surface,
      float surface_water_storage,
      float snow_depth,
      int developmental_stage,
      float crop_reference_evapotranspiration,
      float reference_evapotranspiration,
      float actual_evaporation,
      float actual_transpiration,
      float kc_factor,
      float percentage_soil_coverage,
      float soil_moisture[no_of_soil_layers],
      float permanent_wilting_point[no_of_soil_layers],
      float field_capacity[no_of_soil_layers],
      float evaporation[no_of_soil_layers],
      float transpiration[no_of_soil_layers],
      float crop_transpiration[no_of_soil_layers],
      float crop_remaining_evapotranspiration,
      float crop_evaporated_from_intercepted,
      float evapotranspiration[no_of_soil_layers],
      float actual_evapotranspiration,
      float vapor_pressure):
    evaporated_from_surface, actual_evapotranspiration = model_evapotranspiration(evaporation_zeta,maximum_evaporation_impact_depth,no_of_soil_layers,layer_thickness,reference_albedo,stomata_resistance,evaporation_reduction_method,xsa_critical_soil_moisture,external_reference_evapotranspiration,height_nn,max_air_temperature,min_air_temperature,mean_air_temperature,relative_humidity,wind_speed,wind_speed_height,global_radiation,julian_day,latitude,evaporated_from_surface,surface_water_storage,snow_depth,developmental_stage,crop_reference_evapotranspiration,reference_evapotranspiration,actual_evaporation,actual_transpiration,surface_water_storage,kc_factor,percentage_soil_coverage,soil_moisture,permanent_wilting_point,field_capacity,evaporation,transpiration,crop_transpiration,crop_remaining_evapotranspiration,crop_evaporated_from_intercepted,evapotranspiration,actual_evapotranspiration,vapor_pressure)

    return (evaporated_from_surface, actual_evapotranspiration)